[project]
name = "explainbench"
version = "0.1.0"
"requires-python" = ">=3.12"
dependencies = [
    "swebench == 4.1.0",
    "docker == 7.1.0",
    "dowhen == 0.1.0",
    "litellm == 1.80.11",
    "backoff == 2.2.1",
    "python-dotenv == 1.1.1",
    "pydantic == 2.11.9",
    "tqdm == 4.67.1",
    "numpy == 2.3.3",
    "jq == 1.10.0",
    "asttokens == 3.0.0",
    "pandas == 2.3.2",
    "gitpython == 3.1.45",
    "deepdiff == 8.6.1",
    "datasets == 4.2.0",
    "orjson == 3.11.3",
    "joblib == 1.5.2",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules=[]